create table libreta(
	id_libreta int AUTO_INCREMENT primary key,
	codigo varchar(50),
	nl varchar(50),
	rude varchar(50),
	ci varchar(50),
	pasaporte varchar(50),
	ap_paterno varchar(50),
	ap_materno varchar(50),
	nombre varchar(50),
	sexo varchar(50),
	nacionalidad_nacimiento varchar(50),
	departamento_nacimiento varchar(50),
	provincia_nacimiento varchar(50),
	lugar_nacimiento varchar(50),
	fecha_nacimiento date,
	oficialia varchar(50),
	libro varchar(50),
	partida varchar(50),
	folio varchar(50),
	provincia_o varchar(50),
	seccion varchar(50),
	localidad varchar(50),
	zona varchar(50),
	calle varchar(50),
	numero varchar(50),
	telefono varchar(50),
	pertenece varchar(50),
	n_salud varchar(50),
	trasnporte varchar(50),
	tiempo varchar(50),
	estado varchar(50),
	sie varchar(50),
	nombre_nit varchar(50),
	nit varchar(50),
	codigo_nit varchar(50),
	ci_ap varchar(50),
	nombre_ap varchar(50), -- apoderado
	ap_paterno_ap varchar(50),
	ap_materno_ap varchar(50),
	idioma varchar(50),
	ocupacion varchar(50),
	g_instruccion varchar(50), -- grado de instruccion
	celular_ap varchar(50),
	telefono_ap varchar(50),
	correo_dos varchar(50),
	correo varchar(50),
	email varchar(50),
	realacion varchar(50),
	email_dos varchar(50),
	realacion_dos varchar(50),
	curso varchar(50),
	turno varchar(50),
	nivel varchar(50)
);